// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: affected_area.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AffectedAreaClient is the client API for AffectedArea service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AffectedAreaClient interface {
	CalculateArea(ctx context.Context, in *AffectedAreaRequest, opts ...grpc.CallOption) (*AffectedAreaResponse, error)
}

type affectedAreaClient struct {
	cc grpc.ClientConnInterface
}

func NewAffectedAreaClient(cc grpc.ClientConnInterface) AffectedAreaClient {
	return &affectedAreaClient{cc}
}

func (c *affectedAreaClient) CalculateArea(ctx context.Context, in *AffectedAreaRequest, opts ...grpc.CallOption) (*AffectedAreaResponse, error) {
	out := new(AffectedAreaResponse)
	err := c.cc.Invoke(ctx, "/AffectedArea/calculateArea", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AffectedAreaServer is the server API for AffectedArea service.
// All implementations must embed UnimplementedAffectedAreaServer
// for forward compatibility
type AffectedAreaServer interface {
	CalculateArea(context.Context, *AffectedAreaRequest) (*AffectedAreaResponse, error)
	mustEmbedUnimplementedAffectedAreaServer()
}

// UnimplementedAffectedAreaServer must be embedded to have forward compatible implementations.
type UnimplementedAffectedAreaServer struct {
}

func (UnimplementedAffectedAreaServer) CalculateArea(context.Context, *AffectedAreaRequest) (*AffectedAreaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateArea not implemented")
}
func (UnimplementedAffectedAreaServer) mustEmbedUnimplementedAffectedAreaServer() {}

// UnsafeAffectedAreaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AffectedAreaServer will
// result in compilation errors.
type UnsafeAffectedAreaServer interface {
	mustEmbedUnimplementedAffectedAreaServer()
}

func RegisterAffectedAreaServer(s grpc.ServiceRegistrar, srv AffectedAreaServer) {
	s.RegisterService(&AffectedArea_ServiceDesc, srv)
}

func _AffectedArea_CalculateArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AffectedAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AffectedAreaServer).CalculateArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AffectedArea/calculateArea",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AffectedAreaServer).CalculateArea(ctx, req.(*AffectedAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AffectedArea_ServiceDesc is the grpc.ServiceDesc for AffectedArea service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AffectedArea_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AffectedArea",
	HandlerType: (*AffectedAreaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "calculateArea",
			Handler:    _AffectedArea_CalculateArea_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "affected_area.proto",
}
