// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: diarisation.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiarisationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Audio []byte `protobuf:"bytes,1,opt,name=audio,proto3" json:"audio,omitempty"`
}

func (x *DiarisationRequest) Reset() {
	*x = DiarisationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diarisation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiarisationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiarisationRequest) ProtoMessage() {}

func (x *DiarisationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diarisation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiarisationRequest.ProtoReflect.Descriptor instead.
func (*DiarisationRequest) Descriptor() ([]byte, []int) {
	return file_diarisation_proto_rawDescGZIP(), []int{0}
}

func (x *DiarisationRequest) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

type DiarisationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *DiarisationResponse) Reset() {
	*x = DiarisationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_diarisation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiarisationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiarisationResponse) ProtoMessage() {}

func (x *DiarisationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diarisation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiarisationResponse.ProtoReflect.Descriptor instead.
func (*DiarisationResponse) Descriptor() ([]byte, []int) {
	return file_diarisation_proto_rawDescGZIP(), []int{1}
}

func (x *DiarisationResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_diarisation_proto protoreflect.FileDescriptor

var file_diarisation_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x69, 0x61, 0x72, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x12, 0x44, 0x69, 0x61, 0x72, 0x69, 0x73, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x75, 0x64,
	0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x22,
	0x29, 0x0a, 0x13, 0x44, 0x69, 0x61, 0x72, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x32, 0x4b, 0x0a, 0x0b, 0x44, 0x69,
	0x61, 0x72, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x0f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x13, 0x2e, 0x44,
	0x69, 0x61, 0x72, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x44, 0x69, 0x61, 0x72, 0x69, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2a, 0x5a, 0x28, 0x2e, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x6c, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_diarisation_proto_rawDescOnce sync.Once
	file_diarisation_proto_rawDescData = file_diarisation_proto_rawDesc
)

func file_diarisation_proto_rawDescGZIP() []byte {
	file_diarisation_proto_rawDescOnce.Do(func() {
		file_diarisation_proto_rawDescData = protoimpl.X.CompressGZIP(file_diarisation_proto_rawDescData)
	})
	return file_diarisation_proto_rawDescData
}

var file_diarisation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_diarisation_proto_goTypes = []interface{}{
	(*DiarisationRequest)(nil),  // 0: DiarisationRequest
	(*DiarisationResponse)(nil), // 1: DiarisationResponse
}
var file_diarisation_proto_depIdxs = []int32{
	0, // 0: Diarisation.transcribeAudio:input_type -> DiarisationRequest
	1, // 1: Diarisation.transcribeAudio:output_type -> DiarisationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_diarisation_proto_init() }
func file_diarisation_proto_init() {
	if File_diarisation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_diarisation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiarisationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_diarisation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiarisationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_diarisation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_diarisation_proto_goTypes,
		DependencyIndexes: file_diarisation_proto_depIdxs,
		MessageInfos:      file_diarisation_proto_msgTypes,
	}.Build()
	File_diarisation_proto = out.File
	file_diarisation_proto_rawDesc = nil
	file_diarisation_proto_goTypes = nil
	file_diarisation_proto_depIdxs = nil
}
