// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: iqa.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IQAClient is the client API for IQA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IQAClient interface {
	CalculateQuality(ctx context.Context, in *IQARequest, opts ...grpc.CallOption) (*IQAResponse, error)
}

type iQAClient struct {
	cc grpc.ClientConnInterface
}

func NewIQAClient(cc grpc.ClientConnInterface) IQAClient {
	return &iQAClient{cc}
}

func (c *iQAClient) CalculateQuality(ctx context.Context, in *IQARequest, opts ...grpc.CallOption) (*IQAResponse, error) {
	out := new(IQAResponse)
	err := c.cc.Invoke(ctx, "/IQA/calculateQuality", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IQAServer is the server API for IQA service.
// All implementations must embed UnimplementedIQAServer
// for forward compatibility
type IQAServer interface {
	CalculateQuality(context.Context, *IQARequest) (*IQAResponse, error)
	mustEmbedUnimplementedIQAServer()
}

// UnimplementedIQAServer must be embedded to have forward compatible implementations.
type UnimplementedIQAServer struct {
}

func (UnimplementedIQAServer) CalculateQuality(context.Context, *IQARequest) (*IQAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateQuality not implemented")
}
func (UnimplementedIQAServer) mustEmbedUnimplementedIQAServer() {}

// UnsafeIQAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IQAServer will
// result in compilation errors.
type UnsafeIQAServer interface {
	mustEmbedUnimplementedIQAServer()
}

func RegisterIQAServer(s grpc.ServiceRegistrar, srv IQAServer) {
	s.RegisterService(&IQA_ServiceDesc, srv)
}

func _IQA_CalculateQuality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IQARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IQAServer).CalculateQuality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/IQA/calculateQuality",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IQAServer).CalculateQuality(ctx, req.(*IQARequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IQA_ServiceDesc is the grpc.ServiceDesc for IQA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IQA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "IQA",
	HandlerType: (*IQAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "calculateQuality",
			Handler:    _IQA_CalculateQuality_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iqa.proto",
}
