# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos.affected_area_pb2 as affected__area__pb2


class AffectedAreaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.calculateArea = channel.unary_unary(
                '/AffectedArea/calculateArea',
                request_serializer=affected__area__pb2.AffectedAreaRequest.SerializeToString,
                response_deserializer=affected__area__pb2.AffectedAreaResponse.FromString,
                )


class AffectedAreaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def calculateArea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AffectedAreaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'calculateArea': grpc.unary_unary_rpc_method_handler(
                    servicer.calculateArea,
                    request_deserializer=affected__area__pb2.AffectedAreaRequest.FromString,
                    response_serializer=affected__area__pb2.AffectedAreaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AffectedArea', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AffectedArea(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def calculateArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AffectedArea/calculateArea',
            affected__area__pb2.AffectedAreaRequest.SerializeToString,
            affected__area__pb2.AffectedAreaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
