# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_summarization.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18text_summarization.proto\"\x1f\n\x0fTextSummRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"+\n\x10TextSummResponse\x12\x17\n\x0fsummarized_text\x18\x01 \x01(\t2@\n\x08TextSumm\x12\x34\n\rsummarizeText\x12\x10.TextSummRequest\x1a\x11.TextSummResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_summarization_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXTSUMMREQUEST._serialized_start=28
  _TEXTSUMMREQUEST._serialized_end=59
  _TEXTSUMMRESPONSE._serialized_start=61
  _TEXTSUMMRESPONSE._serialized_end=104
  _TEXTSUMM._serialized_start=106
  _TEXTSUMM._serialized_end=170
# @@protoc_insertion_point(module_scope)
