# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api.iqa_pb2 as iqa__pb2


class IQAStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.calculateQuality = channel.unary_unary(
                '/IQA/calculateQuality',
                request_serializer=iqa__pb2.IQARequest.SerializeToString,
                response_deserializer=iqa__pb2.IQAResponse.FromString,
                )


class IQAServicer(object):
    """Missing associated documentation comment in .proto file."""

    def calculateQuality(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IQAServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'calculateQuality': grpc.unary_unary_rpc_method_handler(
                    servicer.calculateQuality,
                    request_deserializer=iqa__pb2.IQARequest.FromString,
                    response_serializer=iqa__pb2.IQAResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'IQA', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IQA(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def calculateQuality(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IQA/calculateQuality',
            iqa__pb2.IQARequest.SerializeToString,
            iqa__pb2.IQAResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
