# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iqa.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tiqa.proto\"\x1b\n\nIQARequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x1e\n\x0bIQAResponse\x12\x0f\n\x07quality\x18\x01 \x01(\x08\x32\x34\n\x03IQA\x12-\n\x10\x63\x61lculateQuality\x12\x0b.IQARequest\x1a\x0c.IQAResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iqa_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IQAREQUEST._serialized_start=13
  _IQAREQUEST._serialized_end=40
  _IQARESPONSE._serialized_start=42
  _IQARESPONSE._serialized_end=72
  _IQA._serialized_start=74
  _IQA._serialized_end=126
# @@protoc_insertion_point(module_scope)
