# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: diarisation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64iarisation.proto\"#\n\x12\x44iarisationRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"#\n\x13\x44iarisationResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2K\n\x0b\x44iarisation\x12<\n\x0ftranscribeAudio\x12\x13.DiarisationRequest\x1a\x14.DiarisationResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'diarisation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DIARISATIONREQUEST._serialized_start=21
  _DIARISATIONREQUEST._serialized_end=56
  _DIARISATIONRESPONSE._serialized_start=58
  _DIARISATIONRESPONSE._serialized_end=93
  _DIARISATION._serialized_start=95
  _DIARISATION._serialized_end=170
# @@protoc_insertion_point(module_scope)
