DROP DATABASE IF EXISTS hesh;
DROP ROLE IF EXISTS hesh;

CREATE ROLE hesh WITH PASSWORD 'hesh';
ALTER ROLE hesh WITH LOGIN superuser;

CREATE DATABASE hesh
WITH OWNER = hesh
ENCODING = 'UTF8'
TABLESPACE = pg_default
CONNECTION LIMIT = -1;
