# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api.text_summarization_pb2 as text__summarization__pb2


class TextSummStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.summarizeText = channel.unary_unary(
                '/TextSumm/summarizeText',
                request_serializer=text__summarization__pb2.TextSummRequest.SerializeToString,
                response_deserializer=text__summarization__pb2.TextSummResponse.FromString,
                )


class TextSummServicer(object):
    """Missing associated documentation comment in .proto file."""

    def summarizeText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextSummServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'summarizeText': grpc.unary_unary_rpc_method_handler(
                    servicer.summarizeText,
                    request_deserializer=text__summarization__pb2.TextSummRequest.FromString,
                    response_serializer=text__summarization__pb2.TextSummResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TextSumm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TextSumm(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def summarizeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TextSumm/summarizeText',
            text__summarization__pb2.TextSummRequest.SerializeToString,
            text__summarization__pb2.TextSummResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
