// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  domain

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( BasicCommentInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BasicCommentInfo ) UnmarshalJSON([]byte) error { return nil }
func ( BasicCommentInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BasicCommentInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BasicCommentInfo *BasicCommentInfo

func ( CommentCreateResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CommentCreateResponse ) UnmarshalJSON([]byte) error { return nil }
func ( CommentCreateResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CommentCreateResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CommentCreateResponse *CommentCreateResponse

func ( CommentInListInfo ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CommentInListInfo ) UnmarshalJSON([]byte) error { return nil }
func ( CommentInListInfo ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CommentInListInfo ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CommentInListInfo *CommentInListInfo

func ( GetCommentResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetCommentResponse ) UnmarshalJSON([]byte) error { return nil }
func ( GetCommentResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetCommentResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetCommentResponse *GetCommentResponse
